apiVersion: v1
kind: Secret
metadata:
  name: hourly-trading-secrets
type: Opaque
stringData:
  BROKER_API_KEY: "<REPLACE_BROKER_API_KEY>"
  BROKER_API_SECRET: "<REPLACE_BROKER_API_SECRET>"
  BROKER_API_PASSPHRASE: "<REPLACE_BROKER_API_PASSPHRASE_OPTIONAL>"
  BROKER_WS_URL: "<REPLACE_BROKER_WS_URL>"
  BROKER_REPLAY_URL: "<REPLACE_BROKER_REPLAY_URL>"
